disabled_rules:
  - force_cast # todo
  - type_name # todo
  - cyclomatic_complexity # todo
  - trailing_whitespace
  - opening_brace
  - implicit_getter
  - redundant_optional_initialization
  - large_tuple
  - function_body_length

opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma

identifier_name:
  min_length: 1
  excluded:
    - AppUpdateIntervals
    - TemperatureUnits
    - SpeedBase
    - SensorsWidgetMode
    - SpeedPictogram
    - BatteryAdditionals
    - ShortLong
    - ReaderUpdateIntervals
    - NumbersOfProcesses
    - NetworkReaders
    - SensorsList
    - Alignments
    - _devices
    - _uuidAddress
    - AppleSiliconSensorsList
    - FanValues
    - CombinedModulesSpacings
    - BatteryInfo
    - PublicIPAddressRefreshIntervals

line_length: 200

type_body_length:
  - 500
  - 700

file_length:
  - 1200
  - 1600

reporter: "sonarqube"

