name: linter

on:
  push:
    paths:
      - '.github/workflows/linter.yaml'
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/linter.yaml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --output reports/swiftlint.json
